[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' *.openchannel.io; img-src 'self' *.openchannel.io; style-src 'unsafe-inline' 'self'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin"
    Permissions-Policy = "payment 'self'"

[[redirects]]
  from = "/client-api/*"
  to = 'https://7f1ea9e40e2b.ngrok.io/:splat'
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
